dist: focal
language: python

matrix:
    include:
        - python: '3.8'
          env:
          arch: amd64
          arch: arm64
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $PANDAS == "true" ]]; then pip install pandas; fi
    - if [[ $SQLALCHEMY == "true" ]]; then pip install sqlalchemy; fi
    - if [[ $H5PY == "true" ]]; then pip install h5py; fi
    - if [[ $DILL == "true" ]]; then pip install "https://github.com/uqfoundation/dill/archive/master.tar.gz"; fi
    - if [[ $PYTEST == "true" ]]; then pip3 install pytest; fi

install:
    - python setup.py build && python setup.py install

script:
    - pytest
    - for test in tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
